Setting.create!(in_everfree: true, cameo_reversed: false, cameo_position_left: "40%", cameo_position_top: "400px", cameo_width: "200px", pony_reversed: false, pony_position_left: "50%", pony_position_top: "340px", pony_width: "120px", north: 21, south: nil, east: 6, west: 5, name: "Everfree Mirror Pool", img_url:"/assets/everfree_mirror_pond.png")
Setting.create!(in_everfree: true, cameo_reversed: true, cameo_position_left: "40%", cameo_position_top: "600px", cameo_width: "130px", pony_reversed: false, pony_position_left: "60%", pony_position_top: "600px", pony_width: "130px", north: 9, south: nil, east: nil, west: nil, name: "Everfree Row Of Trees By Day", img_url:"/assets/everfree_row_of_trees_by_day.jpg")
Setting.create!(in_everfree: true, cameo_reversed: true, cameo_position_left: "20%", cameo_position_top: "370px", cameo_width: "140px", pony_reversed: false, pony_position_left: "54%", pony_position_top: "385px", pony_width: "80px", north: nil, south: 17, east: 15, west: 14, name: "Everfree Kissing Bridge", img_url:"/assets/everfree_kissing_bridge.png")
Setting.create!(in_everfree: true, cameo_reversed: true, cameo_position_left: "41%", cameo_position_top: "620px", cameo_width: "50px", pony_reversed: false, pony_position_left: "72%", pony_position_top: "525px", pony_width: "80px", north: 16, south: 5, east: 21, west: nil, name: "Everfree Foot of the Mountain", img_url:"/assets/everfree_foot_of_the_mountain.png")
Setting.create!(in_everfree: true, cameo_reversed: true, cameo_position_left: "32%", cameo_position_top: "526px", cameo_width: "100px", pony_reversed: false, pony_position_left: "50%", pony_position_top: "525px", pony_width: "100px", north: 4, south: 8, east: 1, west: nil, name: "Everfree Row of Trees By Night", img_url:"/assets/everfree_row_of_trees_by_night.png")
Setting.create!(in_everfree: true, cameo_reversed: true, cameo_position_left: "25%", cameo_position_top: "300px", cameo_width: "270px", pony_reversed: true, pony_position_left: "55%", pony_position_top: "400px", pony_width: "150px", north: 7, south: 10, east: nil, west: 1, name: "Everfree By The River", img_url:"/assets/everfree_river.png")
Setting.create!(in_everfree: true, cameo_reversed: true, cameo_position_left: "30%", cameo_position_top: "90px", cameo_width: "290px", pony_reversed: false, pony_position_left: "63%", pony_position_top: "360px", pony_width: "200px", north: nil, south: 6, east: 12, west: 21, name: "Everfree Broken Bridge", img_url:"/assets/everfree_broken_bridge.png")
Setting.create!(in_everfree: true, cameo_reversed: false, cameo_position_left: "55%", cameo_position_top: "220px", cameo_width: "380px", pony_reversed: true, pony_position_left: "33%", pony_position_top: "310px", pony_width: "250px", north: 5, south: nil, east: nil, west: nil, name: "Everfree Nice Walk", img_url:"/assets/everfree_nice_walk.png")
Setting.create!(in_everfree: true, cameo_reversed: true, cameo_position_left: "33%", cameo_position_top: "380px", cameo_width: "280px", pony_reversed: false, pony_position_left: "50%", pony_position_top: "330px", pony_width: "150px", north: 20, south: 2, east: nil, west: nil, name: "Everfree Trees With Eyes", img_url:"/assets/everfree_trees_with_eyes.png")

Setting.create!(in_everfree: true, cameo_reversed: false, cameo_position_left: "40%", cameo_position_top: "340px", cameo_width: "200px", pony_reversed: false, pony_position_left: "50%", pony_position_top: "360px", pony_width: "200px", north: 6, south: nil, east: nil, west: nil, name: "Everfree calm_water", img_url:"/assets/everfree_calm_water.png")
Setting.create!(in_everfree: true, cameo_reversed: true, cameo_position_left: "40%", cameo_position_top: "660px", cameo_width: "230px", pony_reversed: false, pony_position_left: "60%", pony_position_top: "695px", pony_width: "150px", north: 13, south: 20, east: nil, west: nil, name: "Everfree Scary Dogs", img_url:"/assets/everfree_scary_dogs.jpg")
Setting.create!(in_everfree: true, cameo_reversed: true, cameo_position_left: "50%", cameo_position_top: "510px", cameo_width: "50px", pony_reversed: false, pony_position_left: "65%", pony_position_top: "450px", pony_width: "150px", north: 19, south: nil, east: 20, west: 7, name: "Everfree Ruins", img_url:"/assets/everfree_ruins.png")
Setting.create!(in_everfree: true, cameo_reversed: false, cameo_position_left: "43%", cameo_position_top: "380px", cameo_width: "270px", pony_reversed: true, pony_position_left: "29%", pony_position_top: "400px", pony_width: "200px", north: nil, south: 11, east: nil, west: nil, name: "Everfree Ferns", img_url:"/assets/everfree_ferns.png")
Setting.create!(in_everfree: true, cameo_reversed: false, cameo_position_left: "59.5%", cameo_position_top: "290px", cameo_width: "160px", pony_reversed: false, pony_position_left: "51%", pony_position_top: "307px", pony_width: "80px", north: nil, south: 16, east: 3, west: nil, name: "Everfree Mountain", img_url:"/assets/everfree_mountain.png")
Setting.create!(in_everfree: true, cameo_reversed: true, cameo_position_left: "25%", cameo_position_top: "400px", cameo_width: "200px", pony_reversed: false, pony_position_left: "55%", pony_position_top: "280px", pony_width: "130px", north: nil, south: nil, east: 18, west: 3, name: "Everfree Rock", img_url:"/assets/everfree_rock.png")
Setting.create!(in_everfree: true, cameo_reversed: false, cameo_position_left: "40%", cameo_position_top: "400px", cameo_width: "200px", pony_reversed: true, pony_position_left: "50%", pony_position_top: "270px", pony_width: "220px", north: 14, south: 4, east: nil, west: nil, name: "Everfree Cliff", img_url:"/assets/everfree_cliff.png")
Setting.create!(in_everfree: true, cameo_reversed: true, cameo_position_left: "38%", cameo_position_top: "470px", cameo_width: "100px", pony_reversed: false, pony_position_left: "44%", pony_position_top: "523px", pony_width: "170px", north: 3, south: 21, east: nil, west: nil, name: "Everfree Fallen Tree", img_url:"/assets/everfree_fallen_tree.jpg")
Setting.create!(in_everfree: true, cameo_reversed: true, cameo_position_left: "33%", cameo_position_top: "345px", cameo_width: "200px", pony_reversed: true, pony_position_left: "40%", pony_position_top: "382px", pony_width: "170px", north: nil, south: 19, east: nil, west: 15, name: "Everfree Mini Cliff", img_url:"/assets/everfree_mini_cliff.png")
Setting.create!(in_everfree: true, cameo_reversed: true, cameo_position_left: "36%", cameo_position_top: "400px", cameo_width: "250px", pony_reversed: false, pony_position_left: "51%", pony_position_top: "350px", pony_width: "180px", north: 18, south: 12, east: nil, west: nil, name: "Everfree Deep Blue", img_url:"/assets/everfree_deep_blue.png")
Setting.create!(in_everfree: true, cameo_reversed: true, cameo_position_left: "33%", cameo_position_top: "360px", cameo_width: "310px", pony_reversed: false, pony_position_left: "59%", pony_position_top: "420px", pony_width: "180px", north: 11, south: 9, east: nil, west: 12, name: "Everfree Between Two Trees", img_url:"/assets/everfree_between_two_trees.png")
Setting.create!(in_everfree: true, cameo_reversed: false, cameo_position_left: "60%", cameo_position_top: "400px", cameo_width: "220px", pony_reversed: true, pony_position_left: "40%", pony_position_top: "450px", pony_width: "120px", north: 17, south: 1, east: nil, west: 4, name: "Everfree Clearing By Night", img_url:"/assets/everfree_clearing_by_night.png")



Pony.create!(name: "Queen Chrysalis", img_url: "http://fc06.deviantart.net/fs71/i/2012/316/d/7/queen_chrysalis_by_proenix-d5ksgw5.png")
Pony.create!(name: "Twilight Sparkle", img_url: "http://www.hasbro.com/mylittlepony/images/carousel/twilight-sparkle-slide.png")
Pony.create!(name: "Pinkie Pie", img_url: "http://www.hasbro.com/mylittlepony/images/carousel/pinkypie-slide.png")
Pony.create!(name: "Fluttershy", img_url: "http://www.hasbro.com/mylittlepony/images/carousel/fluttershy-slide.png")
Pony.create!(name: "Rarity", img_url: "http://www.hasbro.com/mylittlepony/images/carousel/rarity-slide.png")
Pony.create!(name: "Applejack", img_url: "http://www.hasbro.com/mylittlepony/images/carousel/applejack-slide.png")
Pony.create!(name: "Rainbow Dash", img_url: "http://www.hasbro.com/mylittlepony/images/carousel/rainbowdash-slide.png")
Pony.create!(name: "Princess Celestia", img_url: "http://www.hasbro.com/mylittlepony/images/carousel/princesscelestia-slide.png")


Setting.create!(in_everfree: false, name: "Canterlot Sunset", img_url:"http://fc05.deviantart.net/fs70/i/2011/109/9/1/canterlot_sunset___wallpaper_by_crappyunicorn-d3ece2n.jpg")
Setting.create!(in_everfree: false, name: "Canterlot Midday", img_url:"http://images3.wikia.nocookie.net/__cb20120612084332/mlp/pl/images/6/66/Canterlot.png")
Setting.create!(in_everfree: false, name: "Canterlot Winter", img_url:"http://images1.wikia.nocookie.net/__cb20111219011851/mlp/images/9/98/Canterlot_Entrance_S2E11.png")
Setting.create!(in_everfree: false, name: "Canterlot Street By Night", img_url:"http://fc00.deviantart.net/fs71/i/2012/166/e/7/ye_olde_canterlot_by_spiritto-d53lwox.png")
Setting.create!(in_everfree: false, name: "Canterlot Street By Day", img_url:"http://images3.wikia.nocookie.net/__cb20121212070759/mlp/images/e/e0/A_Canterlot_street_S2E9.png")

ClothingItem.create!(dept: "hat", name: "Blue Bow", img_url:"/assets/bluebow.png")
ClothingItem.create!(dept: "hat", name: "Cowboy", img_url:"/assets/cowboyhat.png")
ClothingItem.create!(dept: "hat", name: "Church", img_url:"/assets/finishedchurchhat.png")
ClothingItem.create!(dept: "hat", name: "Church Green", img_url:"/assets/finishedchurchhatGR.png")
ClothingItem.create!(dept: "hat", name: "Church Pink", img_url:"/assets/finishedchurchhatPK.png")
ClothingItem.create!(dept: "hat", name: "Church Yellow", img_url:"/assets/finishedchurchhatYL.png")
ClothingItem.create!(dept: "hat", name: "Purple Bow", img_url:"/assets/purplebow.png")
ClothingItem.create!(dept: "hat", name: "Umbrella", img_url:"/assets/umbrella.png")

ClothingItem.create!(dept: "shoes", name: "Blue Boots", img_url:"/assets/blueboots.png")
ClothingItem.create!(dept: "shoes", name: "Foam", img_url:"/assets/bowseafoam.png")
ClothingItem.create!(dept: "shoes", name: "Converse", img_url:"/assets/converseblack.png")
ClothingItem.create!(dept: "shoes", name: "Orange", img_url:"/assets/orangeshoes.png")
ClothingItem.create!(dept: "shoes", name: "Purple", img_url:"/assets/purpleshoes.png")
ClothingItem.create!(dept: "shoes", name: "Red", img_url:"/assets/red_shoes.png")
ClothingItem.create!(dept: "shoes", name: "Yellow Boots", img_url:"/assets/yellowboots.png")



